version: '3'

services:
  pyspark-jupyter-notebook:
    image: jupyter/pyspark-notebook:latest
    container_name: pyspark-jupyter-notebook
    environment:
      - JUPYTER_TOKEN=${JUPYTER_PYSPARK_TOKEN}
    env_file:
      - ./.env
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan/work/
