services:


  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret
      # - MYSQL_DATABASE=bangladesh_flight
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data: