services:


  mysql:
    image: mysql:latest
    restart: always
    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     interval: 10s
     timeout: 5s
     retries: 5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/sql/mysql:/docker-entrypoint-initdb.d

volumes:
  mysql_data: